name: AndroidBuild

on:
  push:
    branches: [vishu/release]

  pull_request:
    branches: [vishu/release]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

  debug-apk:
    name: Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup the JAVA JDK 17
        uses: actions/setup-java@v1
        with:
          java-version : '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Bulid Debug APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: sample-app.apk
          path: app/build/outputs/apk/debug/app-debug.apk